version: "3.2"

services:
  chat-server:
    build:
      dockerfile: docker/server.dockerfile
      context: .
    command: sh -c './wait-for-it.sh chat-server-db:9042 -- java -jar server.jar --spring.profiles.active=local'
    ports:
    - "8080:8080"
    depends_on:
      - chat-server-db
    networks:
      - chat-server-network

  chat-server-db:
    image: library/cassandra:2.1.21
    networks:
      - chat-server-network
    volumes:
    - "./docker/cassandra/data:/var/lib/cassandra"

networks:
  chat-server-network:
