server:
  port: 8080
springdoc:
  swagger-ui:
    path: /docs/openapi
---
spring:
  profiles: local

cassandra:
  hostname: chat-server-db
  enableMetrics: false
  enableJMXReporting: false
  # set in docker-compose.yml
  keyspace: placeholder
---
spring:
  profiles: production
server:
  address: 192.168.1.120