server:
  port: 8080
---
spring:
  profiles: local

cassandra:
  hostname: chat-server-db
  port: 9042
  enableMetrics: false
  enableJMXReporting: false
---
spring:
  profiles: production
server:
  address: 192.168.1.120